### ISSUE TITLE
Passing all parameters to next function

### ISSUE THREAD

**Issue by marekjm** [marekjm/wudoovm#24]
Implement easy way to call new function with parameters of currently called function.

Ideas:

- `reframe` instruction (create copy of current frame),
- `passargs` instruction (create new frame with same args as current one),

**Comment by marekjm** [comment]
What about tail calls?

Maybe add `tail` instruction that will just inherit current call frame?

**Comment by condret** [comment]
I don't know much about this project, but it looks interresting.
passargs means that you'd have to do memory-movement analysis on the go to differentiate between local vars and args, right? That sounds like a hard task.

**Comment by marekjm** [comment]
Welcome to Wudoo VM and thanks for feedback!

> passargs means that you'd have to do memory-movement analysis on the go to differentiate between local vars and args, right? That sounds like a hard task.

Not quite. Given the architecture of the VM it is actually not a hard task at all. Since I hold each set of call parameters in a separate `Frame` object - kind of like `arguments` array in JavaScript - I can just copy the frame. The only reason I didn't already add this functionality is I have yet to find good use-case fo it.

Below is the explanation of a function call schema:

0. create a `Frame` to hold call parameters: `frame <number of params>`,
0. use either `param` (to copy a value) or `paref` (to put a reference to a value) to fill the frame with parameters: `param <param register> <local register>`,
0. call the function: `call <function name> <return value register>`
0. (inside called function) use `arg <arg register> <local register>` instruction to get call parameters,
0. perform logic,
0. use `end` to return control to caller,

The only minor adjustment I would need to do is that now `arg` instruction *moves* an object instead of *copying* it. So I modify the frame during the function call... Which is not a very good idea...

**Comment by condret** [comment]
the only usecase for this i can imagine are wrappers

**Comment by marekjm** [comment]
I wonder how often one would use this functionality. But it would be much easier than copying the frame manually, when needed.

**Comment by marekjm** [comment]
Closed with issues #44 and #41 . Machine's standard library can be used to achieve functionality described here:

* use `misc::argsvector` from standard `misc` module to obtain copy of parameters,
* then, use `functional::invoke` function from standard `functional` module to invoke needed function,
