### ISSUE TITLE
implement access to syscalls or add software-interrupts

### ISSUE THREAD

**Issue by condret** [marekjm/wudoovm#34]
i think that this is quite important, because somehow you need to enable reading userinput from stdin, opening files or just ptracing a process, if you want to make this productive so that u can use it for other projects

**Comment by marekjm** [comment]
Thanks for feedback! You're right - this is essential functionality.

**Comment by condret** [comment]
btw you could remove the echo and print instruction, they feel somehow inconsistent when if you can use the write-syscall to write to stdout. That does not mean that having printfunctions is bad, but they are stdlib-functions (higher level) and not a part of the instructionset, which is for very lowlevel stuff (moving data and do calculations)

**Comment by marekjm** [comment]
Good idea. They were there to allow me to see what the VM is doing (kind of debugging aid).

**Comment by condret** [comment]
sounds reasonable for debugging-purposes

**Comment by marekjm** [comment]
Update on the "implement access to syscalls" issue. Programs running on the VM can now use functions exported by external modules written in C++. Thus, providing access to syscalls is just a matter of creating a wrapper module for them.

**Comment by marekjm** [comment]
I close the issue as the required machinery is implemented. Now, it is just a matter of implementing a standard library for the machine.
