### ISSUE TITLE
compare + conditional jumps

### ISSUE THREAD

**Issue by condret** [marekjm/wudoovm#38]
I guess you'll need this for more complex stuff than just "hello world".

**Comment by marekjm** [comment]
The VM supports `branch` and `jump` instructions for jumping around.

For comparison there are `eq`, `lt`, `gt` and friends.

**Comment by marekjm** [comment]
You should check out sample programs in the [sample/asm/](https://github.com/marekjm/wudoovm/tree/devel/sample/asm) directory to get the idea of what is possible with Wudoo now.

**Comment by condret** [comment]
oups, sry for that

**Comment by marekjm** [comment]
Just in case: https://github.com/marekjm/wudoovm/blob/devel/src/bytecode/opcodes.h ;-)
